enum Constants {
  SELECT_CHAT = 'SELECT_CHAT',
  DESELECT_CHAT = 'DESELECT_CHAT',
  POPULATE_CHATS = 'POPULATE_CHATS',
  POPULATE_CHAT_MESSAGES = 'POPULATE_CHAT_MESSAGES',
}

export default Constants;
